apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    service: redis
  name: redis-service
  namespace: x4-s24
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  sessionAffinity: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: x4-s24
spec:
  replicas: 1
  updateStrategy:
    type: OnDelete
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
      version: v1
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      priorityClassName: high-priority
      containers:
        - image: pkg.asyx.com:5000/asyx/redis:5.0.5-93
          imagePullPolicy: Always
          name: redis
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
          ports:
          - containerPort: 6379
            name: main
            protocol: TCP
          volumeMounts:
          - name: redis-data
            mountPath: /var/lib/redis
      imagePullSecrets: 
        - name: asyx-docker-prod-secret
      securityContext:
        fsGroup: 445
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: pvc-redis-rancher
