apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: x4-blobstore
  namespace: x4-s24
  name: x4-blobstore-configmap
data:
  application.properties: |
    spring.profiles.active=development
    spring.activemq.broker-url=tcp://activemq-service:61616
    spring.activemq.user=${activemq-user}
    spring.activemq.password=${activemq-password}
    spring.servlet.multipart.max-file-size=50MB
    spring.servlet.multipart.max-request-size=50MB
    spring.redis.url=redis-service
    spring.redis.port=6379
    spring.config.use-legacy-processing=true
    server.port=8080
    server.servlet.contextpath=/
    jwt.signing-key=${jwt-signing-key}
    storage.backend=minio
    feign.blobstore-service=http://x4-blobstore-service:8080/
    minio.bucket-name=blobstore-s24
    minio.endpoint=http://x4-minio-service:9000/
    minio.credentials.access-key=minio
    minio.credentials.secret-key=minio123
    management.endpoints.web.exposure.include=health,info
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: x4-blobstore
  name: x4-blobstore-service
  namespace: x4-s24
spec:
  type: NodePort
  selector:
    app: x4-blobstore
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x4-blobstore
  namespace: x4-s24
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: x4-blobstore
  template:
    metadata:
      labels:
        app: x4-blobstore
        log-format: json
    spec:
      priorityClassName: medium-priority
      containers:
      - name: blobstore
        image: pkg.asyx.com:5000/asyx/x4-blobstore-application:4.3.2-296
        imagePullPolicy: Always
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: jwt-signing-key
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key-secret
              key: secret
        - name: activemq-user
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: activemq-user
        - name: activemq-password
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: activemq-password
        volumeMounts:
        - name: x4-blobstore-config
          mountPath: /x4/config/application.properties
          subPath: application.properties
        - name: blobstore-secret
          mountPath: /x4/config/secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 60
      imagePullSecrets:
      - name: asyx-docker-prod-secret
      volumes:
      - name: x4-blobstore-config
        configMap:
          name: x4-blobstore-configmap
      - name: blobstore-secret
        secret:
          secretName: blobstore-secret